echo "////    Auto-generated by symbol_gen.sh. DO NOT EDIT!" >symbols.c
echo "#include \"include/symbols.h\"" >>symbols.c
echo "const symbol_t __symbol_tab[] = {" >>symbols.c
nm $1 | grep -i " t " | awk '{ print "    { .addr = (void *)0x"$1", .name = \""$3"\" }," }' | sort >>symbols.c
echo "    { .addr = (void *)0xffffffffffffffff, .name = \"\" }};" >>symbols.c
